#!/bin/bash

# Test script for Group DM (MPIM) functionality
# This script tests the Phase 4 implementation

echo "========================================="
echo "Group DM (MPIM) Search Test Script"
echo "========================================="
echo ""
echo "This script tests the following:"
echo "1. Fetching both DM and Group DM channels"
echo "2. Searching within Group DM channels (G...)"
echo "3. Proper display of Group DMs with 👥 prefix"
echo ""
echo "Prerequisites:"
echo "- Your Slack token must have 'im:read', 'mpim:read', 'im:history', and 'mpim:history' scopes"
echo "- You should have at least one Group DM conversation in your Slack workspace"
echo ""
echo "To test manually:"
echo "1. Run the application: npm run tauri dev"
echo "2. Open Settings and ensure your Slack token is configured"
echo "3. Click on the Channel dropdown and enable 'Include DMs'"
echo "4. Look for channels with '@' prefix (regular DMs) and '👥' prefix (Group DMs)"
echo "5. Select a Group DM channel and perform a search"
echo ""
echo "Expected behavior:"
echo "- Group DM channels should appear with '👥' prefix followed by the conversation name"
echo "- Searching in Group DMs should work the same as regular DMs"
echo "- The search should use conversations.history API for both DMs and Group DMs"
echo ""
echo "Check the console logs for:"
echo "- 'Successfully fetched X DM and Y Group DM channels'"
echo "- 'Detected Group DM channel search for: G...'"
echo "- 'Group DM search returned X messages'"
echo ""
echo "========================================="