import type { Message, SlackFile } from '../types/slack';
import { generateFilePlaceholder, generateThumbnailPlaceholder } from '../utils/placeholder';

export const testFiles: SlackFile[] = [
  {
    id: 'F1234567890',
    created: 1699000000,
    timestamp: 1699000000,
    name: 'screenshot.png',
    title: 'App Screenshot',
    mimetype: 'image/png',
    filetype: 'png',
    pretty_type: 'PNG Image',
    user: 'U1234567890',
    username: 'testuser',
    editable: false,
    size: 245678,
    mode: 'hosted',
    is_external: false,
    external_type: '',
    is_public: false,
    public_url_shared: false,
    display_as_bot: false,
    url_private: 'https://files.slack.com/files-pri/T123/F456/screenshot.png',
    url_private_download: 'https://files.slack.com/files-pri/T123/F456/download/screenshot.png',
    permalink: 'https://test.slack.com/files/U123/F456/screenshot.png',
    thumb_64: 'https://files.slack.com/files-tmb/T123/F456/screenshot_64.png',
    thumb_80: 'https://files.slack.com/files-tmb/T123/F456/screenshot_80.png',
    thumb_160: 'https://files.slack.com/files-tmb/T123/F456/screenshot_160.png',
    thumb_360: 'https://files.slack.com/files-tmb/T123/F456/screenshot_360.png',
    thumb_480: 'https://files.slack.com/files-tmb/T123/F456/screenshot_480.png',
    thumb_720: 'https://files.slack.com/files-tmb/T123/F456/screenshot_720.png',
    original_w: 1920,
    original_h: 1080,
    has_rich_preview: true
  },
  {
    id: 'F0987654321',
    created: 1699000100,
    timestamp: 1699000100,
    name: 'document.pdf',
    title: 'Project Proposal',
    mimetype: 'application/pdf',
    filetype: 'pdf',
    pretty_type: 'PDF Document',
    user: 'U1234567890',
    username: 'testuser',
    editable: false,
    size: 1234567,
    mode: 'hosted',
    is_external: false,
    external_type: '',
    is_public: false,
    public_url_shared: false,
    display_as_bot: false,
    url_private: 'https://files.slack.com/files-pri/T123/F789/document.pdf',
    url_private_download: 'https://files.slack.com/files-pri/T123/F789/download/document.pdf',
    permalink: 'https://test.slack.com/files/U123/F789/document.pdf',
    thumb_pdf: 'https://files.slack.com/files-tmb/T123/F789/document_thumb.png',
    preview: 'This is a preview of the PDF content...',
    has_rich_preview: true
  },
  {
    id: 'F1111111111',
    created: 1699000200,
    timestamp: 1699000200,
    name: 'code.js',
    title: 'Sample JavaScript Code',
    mimetype: 'text/javascript',
    filetype: 'javascript',
    pretty_type: 'JavaScript Code',
    user: 'U1234567890',
    username: 'testuser',
    editable: true,
    size: 4567,
    mode: 'snippet',
    is_external: false,
    external_type: '',
    is_public: false,
    public_url_shared: false,
    display_as_bot: false,
    url_private: 'https://files.slack.com/files-pri/T123/F111/code.js',
    url_private_download: 'https://files.slack.com/files-pri/T123/F111/download/code.js',
    permalink: 'https://test.slack.com/files/U123/F111/code.js',
    preview: 'function hello() {\n  console.log("Hello, World!");\n}',
    has_rich_preview: true
  }
];

export function getMockFiles() {
  return {
    image1: {
      id: 'F_IMG_001',
      created: Date.now() / 1000,
      timestamp: Date.now() / 1000,
      name: 'sample-image.jpg',
      title: 'Sample Image',
      mimetype: 'image/jpeg',
      filetype: 'jpg',
      pretty_type: 'JPEG Image',
      user: 'U1234567890',
      username: 'testuser',
      editable: false,
      size: 156789,
      mode: 'hosted',
      is_external: false,
      external_type: '',
      is_public: false,
      public_url_shared: false,
      display_as_bot: false,
      url_private: generateThumbnailPlaceholder(800, 600, 'Sample Image'),
      url_private_download: generateThumbnailPlaceholder(800, 600, 'Sample Image'),
      permalink: 'https://test.slack.com/files/U123/F_IMG_001/sample-image.jpg',
      thumb_64: generateThumbnailPlaceholder(64, 64),
      thumb_80: generateThumbnailPlaceholder(80, 80),
      thumb_160: generateThumbnailPlaceholder(160, 160),
      thumb_360: generateThumbnailPlaceholder(360, 360),
      thumb_480: generateThumbnailPlaceholder(480, 480),
      thumb_720: generateThumbnailPlaceholder(720, 720),
      original_w: 800,
      original_h: 600,
      has_rich_preview: true
    } as SlackFile,
    image2: {
      id: 'F_IMG_002',
      created: Date.now() / 1000,
      timestamp: Date.now() / 1000,
      name: 'screenshot.png',
      title: 'App Screenshot',
      mimetype: 'image/png',
      filetype: 'png',
      pretty_type: 'PNG Image',
      user: 'U1234567890',
      username: 'testuser',
      editable: false,
      size: 245678,
      mode: 'hosted',
      is_external: false,
      external_type: '',
      is_public: false,
      public_url_shared: false,
      display_as_bot: false,
      url_private: generateThumbnailPlaceholder(1920, 1080, 'Screenshot'),
      url_private_download: generateThumbnailPlaceholder(1920, 1080, 'Screenshot'),
      permalink: 'https://test.slack.com/files/U123/F_IMG_002/screenshot.png',
      thumb_64: generateThumbnailPlaceholder(64, 64),
      thumb_80: generateThumbnailPlaceholder(80, 80),
      thumb_160: generateThumbnailPlaceholder(160, 160),
      thumb_360: generateThumbnailPlaceholder(360, 360, 'Screenshot'),
      thumb_480: generateThumbnailPlaceholder(480, 480, 'Screenshot'),
      thumb_720: generateThumbnailPlaceholder(720, 720, 'Screenshot'),
      original_w: 1920,
      original_h: 1080,
      has_rich_preview: true
    } as SlackFile,
    pdf: {
      id: 'F_PDF_001',
      created: Date.now() / 1000,
      timestamp: Date.now() / 1000,
      name: 'document.pdf',
      title: 'Project Proposal',
      mimetype: 'application/pdf',
      filetype: 'pdf',
      pretty_type: 'PDF Document',
      user: 'U1234567890',
      username: 'testuser',
      editable: false,
      size: 1234567,
      mode: 'hosted',
      is_external: false,
      external_type: '',
      is_public: false,
      public_url_shared: false,
      display_as_bot: false,
      url_private: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      url_private_download: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      permalink: 'https://test.slack.com/files/U123/F_PDF_001/document.pdf',
      thumb_pdf: generateFilePlaceholder('pdf', 360),
      preview: 'This is a preview of the PDF content...',
      has_rich_preview: true
    } as SlackFile,
    codeFile: {
      id: 'F_CODE_001',
      created: Date.now() / 1000,
      timestamp: Date.now() / 1000,
      name: 'app.js',
      title: 'Application Code',
      mimetype: 'text/javascript',
      filetype: 'javascript',
      pretty_type: 'JavaScript Code',
      user: 'U1234567890',
      username: 'testuser',
      editable: true,
      size: 4567,
      mode: 'snippet',
      is_external: false,
      external_type: '',
      is_public: false,
      public_url_shared: false,
      display_as_bot: false,
      url_private: 'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/base/common/arrays.ts',
      url_private_download: 'https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/base/common/arrays.ts',
      permalink: 'https://test.slack.com/files/U123/F_CODE_001/app.js',
      preview: `function hello() {
  console.log("Hello, World!");
  return "Hello from JavaScript";
}

const result = hello();
console.log(result);`,
      has_rich_preview: true
    } as SlackFile
  };
}

export const testMessageWithFiles: Message = {
  ts: '1699000000.000000',
  user: 'U1234567890',
  userName: 'Test User',
  text: 'Check out these files I uploaded!',
  channel: 'C1234567890',
  channelName: 'general',
  permalink: 'https://test.slack.com/archives/C123/p1699000000000000',
  isThreadParent: false,
  files: testFiles
};

export const testMessagesWithFiles: Message[] = [
  testMessageWithFiles,
  {
    ts: '1699001000.000000',
    user: 'U0987654321',
    userName: 'Another User',
    text: 'Here is a single image',
    channel: 'C1234567890',
    channelName: 'general',
    permalink: 'https://test.slack.com/archives/C123/p1699001000000000',
    isThreadParent: false,
    files: [testFiles[0]]
  },
  {
    ts: '1699002000.000000',
    user: 'U1122334455',
    userName: 'Third User',
    text: 'PDF document for review',
    channel: 'C1234567890',
    channelName: 'general',
    permalink: 'https://test.slack.com/archives/C123/p1699002000000000',
    isThreadParent: false,
    files: [testFiles[1]]
  }
];